import type { BrushCategory, BrushEngineType, BrushPreset, TipType } from "./types";

type PresetSeed = {
  id: string;
  name: string;
  category: BrushCategory;
  engineType?: BrushEngineType;
  tipType?: TipType;
  size: number;
  opacity?: number;
  flow?: number;
  spacing?: number;
  hardness?: number;
  pressureSize?: number;
  pressureOpacity?: number;
  pressureFlow?: number;
  jitter?: number;
  blend?: string;
  maxSize?: number;
  kind?: "draw" | "erase" | "smudge";
  smoothing?: number;
  stabilization?: number;
  family?: string;
  lineWeightMm?: number;
  scaleAware?: boolean;
  dash?: BrushPreset["dash"];
  grain?: "fine" | "coarse";
};

function preset(seed: PresetSeed): BrushPreset {
  const engineType = seed.engineType ?? "standard";
  const kind = seed.kind ?? "draw";
  return {
    id: seed.id,
    name: seed.name,
    category: seed.category,
    engineType,
    tipType: seed.tipType ?? "round",
    tipImage: null,
    size: seed.size,
    opacity: seed.opacity ?? 1,
    flow: seed.flow ?? 1,
    spacing: seed.spacing ?? 0.06,
    hardness: seed.hardness ?? 1,
    pressureSize: seed.pressureSize ?? 0,
    pressureOpacity: seed.pressureOpacity ?? 0,
    pressureFlow: seed.pressureFlow ?? 0,
    jitter: seed.jitter ?? 0,
    blend:
      seed.blend ??
      (kind === "erase" ? "destination-out" : "source-over"),
    maxSize: seed.maxSize ?? Math.max(40, seed.size * 4),
    kind,
    smoothing: seed.smoothing ?? 0.35,
    stabilization: seed.stabilization ?? 0.2,
    scaleAware: seed.scaleAware
      ? {
          enabled: true,
          lineWeightMm: seed.lineWeightMm,
          class:
            seed.lineWeightMm && seed.lineWeightMm <= 0.1
              ? "extra-fine"
              : seed.lineWeightMm && seed.lineWeightMm <= 0.18
                ? "fine"
                : seed.lineWeightMm && seed.lineWeightMm <= 0.35
                  ? "medium"
                  : seed.lineWeightMm && seed.lineWeightMm <= 0.7
                    ? "heavy"
                    : "extra-heavy",
        }
      : undefined,
    dash: seed.dash,
    family: seed.family,
    builtIn: true,
    source: "built-in",
    version: 1,
    grain: seed.grain,
  };
}

/** Recommended Phase 1–2 release library (~45 brushes). */
export const BUILTIN_BRUSH_PRESETS: BrushPreset[] = [
  // Technical
  preset({
    id: "tech-xfine",
    name: "Technical Extra Fine",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1,
    lineWeightMm: 0.08,
    scaleAware: true,
    pressureSize: 0.1,
    smoothing: 0.45,
  }),
  preset({
    id: "tech-fine",
    name: "Technical Fine",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.4,
    lineWeightMm: 0.15,
    scaleAware: true,
    smoothing: 0.4,
  }),
  preset({
    id: "tech-medium",
    name: "Technical Medium",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 2.2,
    lineWeightMm: 0.3,
    scaleAware: true,
    pressureSize: 0.15,
  }),
  preset({
    id: "tech-heavy",
    name: "Technical Heavy",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 3.5,
    lineWeightMm: 0.6,
    scaleAware: true,
  }),
  preset({
    id: "scalepen-fine",
    name: "ScalePen Fine",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.5,
    lineWeightMm: 0.18,
    scaleAware: true,
    smoothing: 0.5,
  }),
  preset({
    id: "scalepen-medium",
    name: "ScalePen Medium",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 2.4,
    lineWeightMm: 0.35,
    scaleAware: true,
    smoothing: 0.5,
  }),
  preset({
    id: "scalepen-heavy",
    name: "ScalePen Heavy",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 4,
    lineWeightMm: 0.7,
    scaleAware: true,
    smoothing: 0.45,
  }),
  preset({
    id: "tech-dashed",
    name: "Dashed Technical",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.6,
    lineWeightMm: 0.25,
    scaleAware: true,
    dash: { enabled: true, pattern: "dashed", dashMm: 4, gapMm: 2 },
  }),
  preset({
    id: "tech-centerline",
    name: "Centerline",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.3,
    lineWeightMm: 0.18,
    scaleAware: true,
    dash: { enabled: true, pattern: "centerline", dashMm: 8, gapMm: 2 },
  }),
  preset({
    id: "tech-construction",
    name: "Construction Pen",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.2,
    opacity: 0.35,
    lineWeightMm: 0.13,
    scaleAware: true,
  }),
  preset({
    id: "tech-revision",
    name: "Revision Pen",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 2.5,
    opacity: 0.95,
    pressureSize: 0.2,
  }),

  // Quick-access aliases (rail tools)
  // Tuned to Morpholio Trace / Sketchbook Pro feel:
  // Fine/Technical ≈ constant width; Brush Nib / Fountain ≈ high pressure taper;
  // Markers ≈ translucent multiply; Pencils ≈ grain + opacity pressure.
  preset({
    id: "pen",
    name: "Fine Pen",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.8,
    hardness: 1,
    // Trace Fine / Ultra Fine: crisp, nearly constant width (not brush-like taper)
    pressureSize: 0.12,
    pressureOpacity: 0,
    maxSize: 12,
    smoothing: 0.4,
    stabilization: 0.22,
  }),
  preset({
    id: "technicalpen",
    name: "Technical Pen",
    category: "technical",
    engineType: "technical",
    family: "pen",
    size: 1.4,
    hardness: 1,
    pressureSize: 0,
    pressureOpacity: 0,
    lineWeightMm: 0.25,
    scaleAware: true,
    maxSize: 12,
    smoothing: 0.5,
    stabilization: 0.28,
  }),
  preset({
    id: "fountainpen",
    name: "Fountain Pen",
    category: "ink",
    engineType: "standard",
    family: "pen",
    // Trace Brush Nib Marker: thin↔thick with pressure
    size: 3.2,
    pressureSize: 0.92,
    pressureOpacity: 0.1,
    maxSize: 28,
    smoothing: 0.32,
  }),
  preset({
    id: "ballpoint",
    name: "Ballpoint",
    category: "ink",
    engineType: "standard",
    family: "pen",
    size: 1.15,
    opacity: 0.58,
    pressureSize: 0.28,
    pressureOpacity: 0.4,
    jitter: 0.04,
    maxSize: 8,
    smoothing: 0.28,
  }),

  // Pencil
  preset({
    id: "pencil",
    name: "HB Pencil",
    category: "pencil",
    tipType: "soft",
    family: "pencil",
    // Trace Graphite Pencil: soft edge, strong opacity pressure, light tooth
    size: 1.6,
    opacity: 0.72,
    hardness: 0.45,
    pressureSize: 0.55,
    pressureOpacity: 0.62,
    jitter: 0.12,
    maxSize: 10,
    grain: "fine",
    smoothing: 0.28,
  }),
  preset({
    id: "mechanicalpencil",
    name: "Mechanical Pencil",
    category: "pencil",
    tipType: "soft",
    family: "pencil",
    size: 1.1,
    opacity: 0.78,
    hardness: 0.75,
    pressureSize: 0.22,
    pressureOpacity: 0.35,
    jitter: 0.03,
    maxSize: 6,
  }),
  preset({
    id: "pencil-2b",
    name: "2B Pencil",
    category: "pencil",
    tipType: "soft",
    family: "pencil",
    size: 2.4,
    opacity: 0.78,
    hardness: 0.38,
    pressureSize: 0.75,
    pressureOpacity: 0.7,
    jitter: 0.18,
    grain: "fine",
  }),
  preset({
    id: "pencil-4b",
    name: "4B Pencil",
    category: "pencil",
    tipType: "soft",
    family: "pencil",
    size: 3.6,
    opacity: 0.82,
    hardness: 0.28,
    pressureSize: 0.9,
    pressureOpacity: 0.78,
    jitter: 0.22,
    grain: "coarse",
  }),
  preset({
    id: "pencil-rough",
    name: "Rough Pencil",
    category: "pencil",
    tipType: "texture",
    family: "pencil",
    size: 4.2,
    opacity: 0.68,
    hardness: 0.22,
    pressureSize: 0.75,
    pressureOpacity: 0.6,
    jitter: 0.42,
    grain: "coarse",
  }),
  preset({
    id: "pencil-shading",
    name: "Shading Pencil",
    category: "pencil",
    tipType: "soft",
    family: "pencil",
    size: 14,
    opacity: 0.28,
    hardness: 0.15,
    pressureSize: 0.4,
    pressureOpacity: 0.9,
    spacing: 0.12,
  }),
  // Morpholio Grease Pencil — waxy, opaque, soft edge
  preset({
    id: "grease-pencil",
    name: "Grease Pencil",
    category: "dry-media",
    tipType: "soft",
    family: "pencil",
    size: 5,
    opacity: 0.92,
    hardness: 0.35,
    pressureSize: 0.45,
    pressureOpacity: 0.25,
    jitter: 0.08,
    maxSize: 28,
  }),
  // Morpholio Charcoal — dusty, high tooth, strong pressure
  preset({
    id: "charcoal",
    name: "Charcoal",
    category: "dry-media",
    tipType: "texture",
    family: "pencil",
    size: 8,
    opacity: 0.75,
    hardness: 0.18,
    pressureSize: 0.85,
    pressureOpacity: 0.7,
    jitter: 0.5,
    grain: "coarse",
    maxSize: 48,
  }),

  // Ink
  preset({
    id: "fineliner",
    name: "Fineliner",
    category: "ink",
    engineType: "standard",
    // Trace Ultra Fine Marker — razor constant width
    size: 1.15,
    hardness: 1,
    pressureSize: 0.04,
    pressureOpacity: 0,
    smoothing: 0.45,
    maxSize: 6,
  }),
  preset({
    id: "brushpen",
    name: "Brush Pen",
    category: "ink",
    tipType: "soft",
    // Trace Brush Nib Marker
    size: 5.5,
    hardness: 0.55,
    pressureSize: 0.96,
    pressureOpacity: 0.18,
    maxSize: 42,
    smoothing: 0.3,
  }),
  preset({
    id: "chiselpen",
    name: "Chisel Pen",
    category: "ink",
    tipType: "chisel",
    size: 9,
    hardness: 0.95,
    pressureSize: 0.25,
    maxSize: 36,
  }),

  // Markers — Trace Fine / Chisel / Alcohol: translucent multiply layers
  preset({
    id: "marker",
    name: "Marker",
    category: "marker",
    engineType: "marker",
    tipType: "soft",
    size: 14,
    opacity: 0.42,
    hardness: 0.55,
    pressureSize: 0.08,
    pressureOpacity: 0.22,
    blend: "multiply",
    maxSize: 60,
    smoothing: 0.22,
  }),
  preset({
    id: "marker-fine",
    name: "Fine Marker",
    category: "marker",
    engineType: "marker",
    tipType: "soft",
    size: 5,
    opacity: 0.48,
    hardness: 0.65,
    pressureSize: 0.06,
    blend: "multiply",
    maxSize: 24,
  }),
  preset({
    id: "marker-broad",
    name: "Broad Marker",
    category: "marker",
    engineType: "marker",
    tipType: "soft",
    size: 30,
    opacity: 0.38,
    hardness: 0.5,
    blend: "multiply",
    maxSize: 90,
  }),
  preset({
    id: "marker-chisel",
    name: "Chisel Marker",
    category: "marker",
    engineType: "marker",
    tipType: "chisel",
    size: 18,
    opacity: 0.45,
    hardness: 0.9,
    pressureSize: 0.15,
    blend: "multiply",
    maxSize: 56,
  }),
  preset({
    id: "marker-transparent",
    name: "Transparent Marker",
    category: "marker",
    engineType: "marker",
    tipType: "soft",
    size: 16,
    opacity: 0.24,
    hardness: 0.4,
    blend: "multiply",
    pressureOpacity: 0.45,
  }),
  preset({
    id: "highlighter",
    name: "Highlighter",
    category: "marker",
    engineType: "marker",
    tipType: "flat",
    size: 24,
    opacity: 0.2,
    hardness: 0.7,
    blend: "multiply",
    maxSize: 80,
  }),
  preset({
    id: "marker-arch",
    name: "Architectural Marker",
    category: "marker",
    engineType: "marker",
    tipType: "chisel",
    size: 14,
    opacity: 0.36,
    blend: "multiply",
    hardness: 0.85,
    pressureSize: 0.12,
  }),
  preset({
    id: "marker-alcohol",
    name: "Alcohol Marker",
    category: "marker",
    engineType: "marker",
    tipType: "soft",
    size: 16,
    opacity: 0.3,
    hardness: 0.35,
    blend: "multiply",
    pressureOpacity: 0.4,
    pressureSize: 0.2,
  }),

  // Paint / render
  preset({
    id: "brush",
    name: "Round Brush",
    category: "paint",
    engineType: "paint",
    tipType: "soft",
    size: 9,
    opacity: 0.88,
    hardness: 0.55,
    pressureSize: 0.88,
    pressureOpacity: 0.15,
    maxSize: 80,
  }),
  preset({
    id: "paint-flat",
    name: "Flat Brush",
    category: "paint",
    engineType: "paint",
    tipType: "flat",
    size: 14,
    hardness: 0.9,
    pressureSize: 0.35,
  }),
  preset({
    id: "paint-dry",
    name: "Dry Brush",
    category: "paint",
    engineType: "paint",
    tipType: "texture",
    size: 16,
    opacity: 0.65,
    hardness: 0.3,
    jitter: 0.3,
    pressureSize: 0.5,
    grain: "coarse",
  }),
  preset({
    id: "watercolour",
    name: "Watercolour Round",
    category: "watercolor",
    engineType: "watercolor",
    tipType: "soft",
    // Trace Watercolor: very soft, translucent, builds with pressure
    size: 30,
    opacity: 0.12,
    hardness: 0.12,
    pressureSize: 0.85,
    pressureOpacity: 0.85,
    jitter: 0.06,
    blend: "multiply",
    flow: 0.75,
    maxSize: 160,
    smoothing: 0.42,
  }),
  preset({
    id: "wc-wash",
    name: "Watercolor Wash",
    category: "watercolor",
    engineType: "watercolor",
    tipType: "soft",
    size: 52,
    opacity: 0.08,
    hardness: 0.06,
    blend: "multiply",
    pressureOpacity: 0.7,
    maxSize: 220,
  }),
  preset({
    id: "wc-wet",
    name: "Wet Watercolor",
    category: "watercolor",
    engineType: "watercolor",
    tipType: "soft",
    size: 34,
    opacity: 0.1,
    hardness: 0.05,
    blend: "multiply",
    pressureSize: 0.7,
    pressureOpacity: 0.92,
  }),
  preset({
    id: "roller",
    name: "Solid Roller",
    category: "paint",
    engineType: "roller",
    tipType: "flat",
    // Trace Roller Brush — dense fill, little pressure response
    size: 42,
    opacity: 0.9,
    hardness: 0.95,
    spacing: 0.12,
    pressureSize: 0.05,
    maxSize: 160,
  }),
  preset({
    id: "airbrush-soft",
    name: "Soft Airbrush",
    category: "airbrush",
    tipType: "soft",
    size: 40,
    opacity: 0.14,
    hardness: 0.04,
    pressureOpacity: 0.75,
    pressureSize: 0.25,
    spacing: 0.07,
    maxSize: 180,
  }),
  preset({
    id: "airbrush-hard",
    name: "Hard Airbrush",
    category: "airbrush",
    tipType: "soft",
    size: 22,
    opacity: 0.26,
    hardness: 0.4,
    pressureOpacity: 0.55,
    pressureSize: 0.2,
  }),

  // Texture / landscape
  preset({
    id: "tex-concrete",
    name: "Concrete",
    category: "texture",
    engineType: "texture",
    tipType: "texture",
    size: 20,
    opacity: 0.55,
    jitter: 0.35,
    grain: "coarse",
  }),
  preset({
    id: "tex-wood",
    name: "Wood Grain",
    category: "texture",
    engineType: "texture",
    tipType: "texture",
    size: 16,
    opacity: 0.6,
    jitter: 0.2,
    grain: "fine",
  }),
  preset({
    id: "tex-stone",
    name: "Stone",
    category: "texture",
    engineType: "texture",
    tipType: "texture",
    size: 18,
    opacity: 0.55,
    grain: "coarse",
  }),
  preset({
    id: "tex-brick",
    name: "Brick",
    category: "architectural",
    engineType: "texture",
    tipType: "texture",
    size: 14,
    opacity: 0.7,
    grain: "coarse",
  }),
  preset({
    id: "tex-grass",
    name: "Grass",
    category: "landscape",
    engineType: "texture",
    tipType: "texture",
    size: 12,
    opacity: 0.65,
    jitter: 0.5,
    grain: "fine",
  }),
  preset({
    id: "tex-foliage",
    name: "Foliage",
    category: "landscape",
    engineType: "texture",
    tipType: "texture",
    size: 22,
    opacity: 0.5,
    jitter: 0.45,
    grain: "coarse",
  }),
  preset({
    id: "tex-speckle",
    name: "Speckle",
    category: "effects",
    engineType: "texture",
    tipType: "texture",
    size: 10,
    opacity: 0.7,
    jitter: 0.6,
    grain: "fine",
  }),
  preset({
    id: "tex-hatch",
    name: "Crosshatch",
    category: "architectural",
    engineType: "texture",
    tipType: "texture",
    size: 8,
    opacity: 0.8,
    spacing: 0.2,
    grain: "fine",
  }),

  // Editing
  preset({
    id: "eraser",
    name: "Hard Eraser",
    category: "eraser",
    engineType: "eraser",
    size: 24,
    hardness: 0.95,
    pressureSize: 0.25,
    kind: "erase",
    maxSize: 100,
  }),
  preset({
    id: "eraser-soft",
    name: "Soft Eraser",
    category: "eraser",
    engineType: "eraser",
    tipType: "soft",
    size: 28,
    hardness: 0.25,
    pressureSize: 0.4,
    pressureOpacity: 0.5,
    kind: "erase",
    maxSize: 120,
  }),
  preset({
    id: "smudge",
    name: "Smudge",
    category: "blend",
    engineType: "smudge",
    tipType: "soft",
    size: 18,
    opacity: 0.6,
    hardness: 0.3,
    kind: "smudge",
    maxSize: 80,
  }),
  preset({
    id: "blend-natural",
    name: "Natural Blend",
    category: "blend",
    engineType: "smudge",
    tipType: "soft",
    size: 22,
    opacity: 0.45,
    hardness: 0.2,
    kind: "smudge",
  }),
];

export const BRUSH_CATEGORY_LABELS: Record<BrushCategory, string> = {
  technical: "Technical",
  pencil: "Pencil",
  ink: "Inking",
  marker: "Markers",
  paint: "Paint",
  watercolor: "Watercolor",
  airbrush: "Airbrush",
  "dry-media": "Dry Media",
  texture: "Texture",
  landscape: "Landscape",
  effects: "Effects",
  blend: "Blending",
  eraser: "Erasers",
  architectural: "Architectural",
  imported: "Imported",
  user: "My Brushes",
};

/** Rail quick tools + family membership for UI. */
export const BRUSH_FAMILIES: Record<string, string[]> = {
  pen: [
    "pen",
    "fineliner",
    "technicalpen",
    "fountainpen",
    "brushpen",
    "ballpoint",
    "chiselpen",
    "tech-xfine",
    "tech-fine",
    "tech-medium",
    "tech-heavy",
    "scalepen-fine",
    "scalepen-medium",
    "scalepen-heavy",
    "tech-dashed",
    "tech-centerline",
    "tech-construction",
    "tech-revision",
  ],
  pencil: [
    "pencil",
    "mechanicalpencil",
    "pencil-2b",
    "pencil-4b",
    "pencil-rough",
    "pencil-shading",
    "grease-pencil",
    "charcoal",
  ],
};

export function getBuiltinBrush(id: string): BrushPreset | undefined {
  return BUILTIN_BRUSH_PRESETS.find((b) => b.id === id);
}
